### ISSUE TITLE
this is blargboard 1.1

### ISSUE THREAD

**Issue by ghost** [RoadrunnerWMC/Blargboard-1.1#1]
not blargboard 1.2

just sayin

**Comment by phase** [comment]
[Here](https://github.com/TomokoTomoki/Blargboard) is 1.2

**Comment by RoadrunnerWMC** [comment]
The version is displayed clearly now. Thanks to both of you for reporting this. :)

**Comment by phase** [comment]
I made a [differences](https://github.com/phase/blargtest/blob/master/differences.patch) file that, as the name may suggest, shows the differences between 1.1 and 1.2. Not much changed. Here's what I've been able to gather:
- Some notification changes (not sure if these are super important or not)
- Inner global variables were changed to environment variables
- URL fetching changes (code just made better)
- Small CSS changes
